/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/NVM.glb -o src/components/Nvm.jsx -r public 
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { easing } from "maath";
import { useFrame, useThree } from "@react-three/fiber";

export function Nvm (props, ref) {
  const group = useRef();
  
  const { nodes, materials, animations } = useGLTF("/models/NVM.glb");
  const { actions } = useAnimations(animations, group);

  const scene = useThree();
  // useFrame((state, delta) => {

  //   easing.damp3(group.current.position, [
  //     state.pointer.x * 0.1, // Adjust position on X-axis based on mouseX
  //     -state.pointer.y * 0.1, // Adjust position on Y-axis based on mouseY
  //     0
  //   ], 1, delta);

  // })
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="WHITE-robo001"
          position={[129.16, -0.722, -148.919]}
          rotation={[0, 0.436, 0]}
          scale={2.071}
        >
          <group
            name="Robo_weiß001"
            position={[9.831, 0.328, 0.003]}
            scale={0.735}
          >
            <group name="Bone_4" position={[0, -0.289, -0.047]}>
              <group
                name="Bone001_4"
                position={[0, 0.038, 0]}
                rotation={[-0.368, 0, 0]}
              >
                <group
                  name="Bone002_4"
                  position={[0, 0.328, 0]}
                  rotation={[1.426, 0, 0]}
                >
                  <group
                    name="Bone003_4"
                    position={[0, 0.349, 0]}
                    rotation={[0.513, 0, 0]}
                  >
                    <group
                      name="Cube020"
                      position={[-0.001, 0.013, -0.001]}
                      rotation={[-Math.PI / 2, 0, 0]}
                    >
                      <mesh
                        name="Cube037_1"
                        geometry={nodes.Cube037_1.geometry}
                        material={materials["metal-Black-grey-dird.002"]}
                      />
                      <mesh
                        name="Cube037_2"
                        geometry={nodes.Cube037_2.geometry}
                        material={materials["weiß-metall"]}
                      />
                    </group>
                  </group>
                  <group
                    name="Cube019"
                    position={[0.004, 0.178, -0.001]}
                    rotation={[-1.058, 0, 0]}
                  >
                    <mesh
                      name="Cube038"
                      geometry={nodes.Cube038.geometry}
                      material={materials["weiß-metall"]}
                    />
                    <mesh
                      name="Cube038_1"
                      geometry={nodes.Cube038_1.geometry}
                      material={materials["Plasti.blackl"]}
                    />
                  </group>
                </group>
                <group
                  name="Cylinder025"
                  position={[0, 0.315, 0.003]}
                  rotation={[0.368, 0, 0]}
                >
                  <mesh
                    name="Cylinder007"
                    geometry={nodes.Cylinder007.geometry}
                    material={materials["weiß-metall"]}
                  />
                  <mesh
                    name="Cylinder007_1"
                    geometry={nodes.Cylinder007_1.geometry}
                    material={materials["Plasti.blackl"]}
                  />
                </group>
              </group>
              <mesh
                name="Cylinder026"
                geometry={nodes.Cylinder026.geometry}
                material={materials["metal-Black-grey-dird.002"]}
                position={[0, -0.004, 0.012]}
              />
            </group>
          </group>
        </group>
        <group
          name="WHITE-robo"
          position={[152.272, -0.903, -151.122]}
          rotation={[-Math.PI, 0.579, -Math.PI]}
          scale={2.287}
        >
          <group
            name="Robo_weiß001_1"
            position={[9.831, 0.328, 0.003]}
            scale={0.735}
          >
            <group name="Bone_5" position={[0, -0.289, -0.047]}>
              <group
                name="Bone001_5"
                position={[0, 0.038, 0]}
                rotation={[-0.368, 0, 0]}
              >
                <group
                  name="Bone002_5"
                  position={[0, 0.328, 0]}
                  rotation={[1.426, 0, 0]}
                >
                  <group
                    name="Bone003_5"
                    position={[0, 0.349, 0]}
                    rotation={[0.513, 0, 0]}
                  >
                    <group
                      name="Cube020_1"
                      position={[-0.001, 0.013, -0.001]}
                      rotation={[-Math.PI / 2, 0, 0]}
                    >
                      <mesh
                        name="Cube037_1"
                        geometry={nodes.Cube037_1.geometry}
                        material={materials["metal-Black-grey-dird.002"]}
                      />
                      <mesh
                        name="Cube037_2"
                        geometry={nodes.Cube037_2.geometry}
                        material={materials["weiß-metall"]}
                      />
                    </group>
                  </group>
                  <group
                    name="Cube019_1"
                    position={[0.004, 0.178, -0.001]}
                    rotation={[-1.058, 0, 0]}
                  >
                    <mesh
                      name="Cube038"
                      geometry={nodes.Cube038.geometry}
                      material={materials["weiß-metall"]}
                    />
                    <mesh
                      name="Cube038_1"
                      geometry={nodes.Cube038_1.geometry}
                      material={materials["Plasti.blackl"]}
                    />
                  </group>
                </group>
                <group
                  name="Cylinder025_1"
                  position={[0, 0.315, 0.003]}
                  rotation={[0.368, 0, 0]}
                >
                  <mesh
                    name="Cylinder007"
                    geometry={nodes.Cylinder007.geometry}
                    material={materials["weiß-metall"]}
                  />
                  <mesh
                    name="Cylinder007_1"
                    geometry={nodes.Cylinder007_1.geometry}
                    material={materials["Plasti.blackl"]}
                  />
                </group>
              </group>
              <mesh
                name="Cylinder026_1"
                geometry={nodes.Cylinder026_1.geometry}
                material={materials["metal-Black-grey-dird.002"]}
                position={[0, -0.004, 0.012]}
              />
            </group>
          </group>
        </group>
        <group
          name="Armature001"
          position={[133.549, 0.524, -150.068]}
          scale={0.826}
        >
          <group
            name="Bone"
            position={[0.017, -0.84, -0.489]}
            rotation={[-1.09, 0.033, 0.064]}
          >
            <group
              name="Bone001"
              position={[0, 0.372, 0]}
              rotation={[2.45, 0, 0]}
            >
              <group
                name="Bone002"
                position={[-0.19, 1.114, -0.001]}
                rotation={[-1.856, 0, 0]}
              >
                <group
                  name="Bone003"
                  position={[0.154, 1.097, 0.009]}
                  rotation={[1.895, 0, 0]}
                >
                  <group
                    name="Bone004"
                    position={[0, 0.902, 0]}
                    rotation={[0.809, 0, 0.01]}
                  >
                    <group
                      name="Cube016"
                      position={[-0.004, 0.095, -0.001]}
                      rotation={[0.645, -0.001, 3.128]}
                    >
                      <mesh
                        name="Cube022"
                        geometry={nodes.Cube022.geometry}
                        material={materials["Plasti.blackl"]}
                      />
                      <mesh
                        name="Cube022_1"
                        geometry={nodes.Cube022_1.geometry}
                        material={materials["orange.001"]}
                      />
                    </group>
                  </group>
                  <mesh
                    name="Cube017"
                    geometry={nodes.Cube017.geometry}
                    material={materials["orange.001"]}
                    position={[-0.002, 0.123, -0.002]}
                    rotation={[1.495, 0.005, 3.136]}
                  />
                </group>
                <group
                  name="Cylinder002"
                  position={[0.024, 0.376, -0.005]}
                  rotation={[-2.693, 0.005, 3.136]}
                >
                  <mesh
                    name="Cylinder005"
                    geometry={nodes.Cylinder005.geometry}
                    material={materials["orange.001"]}
                  />
                  <mesh
                    name="Cylinder005_1"
                    geometry={nodes.Cylinder005_1.geometry}
                    material={materials["Plasti.blackl"]}
                  />
                </group>
              </group>
              <group
                name="Cylinder001"
                position={[-0.014, 0.661, -0.003]}
                rotation={[1.696, 0.005, 3.136]}
              >
                <mesh
                  name="Cylinder004_1"
                  geometry={nodes.Cylinder004_1.geometry}
                  material={materials["orange.001"]}
                />
                <mesh
                  name="Cylinder004_2"
                  geometry={nodes.Cylinder004_2.geometry}
                  material={materials["Plasti.blackl"]}
                />
              </group>
            </group>
            <mesh
              name="Cube011"
              geometry={nodes.Cube011.geometry}
              material={materials["Plasti.blackl"]}
              position={[-0.017, -0.063, -0.084]}
              rotation={[-2.052, 0.005, -Math.PI]}
            />
          </group>
        </group>
        <group
          name="Robo_gelb002"
          position={[138.098, -0.597, -156.321]}
          rotation={[0, -1.571, 0]}
          scale={1.959}
        >
          <group name="Bone_1" position={[0.001, -0.002, -0.004]}>
            <group
              name="Bone001_1"
              position={[0, 0.038, 0]}
              rotation={[-0.368, 0, 0]}
            >
              <group
                name="Bone002_1"
                position={[0, 0.328, 0]}
                rotation={[1.426, 0, 0]}
              >
                <group
                  name="Bone003_1"
                  position={[0, 0.349, 0]}
                  rotation={[0.513, 0, 0]}
                >
                  <group
                    name="Cube037"
                    position={[-0.001, 0.013, -0.001]}
                    rotation={[-Math.PI / 2, 0, 0]}
                  >
                    <mesh
                      name="Cube060"
                      geometry={nodes.Cube060.geometry}
                      material={materials["metal-Black-grey-dird.002"]}
                    />
                    <mesh
                      name="Cube060_1"
                      geometry={nodes.Cube060_1.geometry}
                      material={materials["gelb.metal.001"]}
                    />
                  </group>
                </group>
                <group
                  name="Cube036"
                  position={[0.004, 0.178, -0.001]}
                  rotation={[-1.058, 0, 0]}
                >
                  <mesh
                    name="Cube059_1"
                    geometry={nodes.Cube059_1.geometry}
                    material={materials["gelb.metal.001"]}
                  />
                  <mesh
                    name="Cube059_2"
                    geometry={nodes.Cube059_2.geometry}
                    material={materials["Plasti.blackl"]}
                  />
                </group>
              </group>
              <group
                name="Cylinder003"
                position={[0, 0.315, 0.003]}
                rotation={[0.368, 0, 0]}
              >
                <mesh
                  name="Cylinder038"
                  geometry={nodes.Cylinder038.geometry}
                  material={materials["gelb.metal.001"]}
                />
                <mesh
                  name="Cylinder038_1"
                  geometry={nodes.Cylinder038_1.geometry}
                  material={materials["Plasti.blackl"]}
                />
              </group>
            </group>
            <mesh
              name="Cylinder024"
              geometry={nodes.Cylinder024.geometry}
              material={materials["metal-Black-grey-dird.002"]}
              position={[0, -0.004, 0.012]}
            />
          </group>
        </group>
        <group
          name="Robo_gelb001"
          position={[134.279, -0.597, -156.321]}
          rotation={[0, -1.571, 0]}
          scale={1.959}
        >
          <group name="Bone_2" position={[0.001, -0.002, -0.004]}>
            <group
              name="Bone001_2"
              position={[0, 0.038, 0]}
              rotation={[-0.368, 0, 0]}
            >
              <group
                name="Bone002_2"
                position={[0, 0.328, 0]}
                rotation={[1.426, 0, 0]}
              >
                <group
                  name="Bone003_2"
                  position={[0, 0.349, 0]}
                  rotation={[0.513, 0, 0]}
                >
                  <group
                    name="Cube035"
                    position={[-0.001, 0.013, -0.001]}
                    rotation={[-Math.PI / 2, 0, 0]}
                  >
                    <mesh
                      name="Cube060"
                      geometry={nodes.Cube060.geometry}
                      material={materials["metal-Black-grey-dird.002"]}
                    />
                    <mesh
                      name="Cube060_1"
                      geometry={nodes.Cube060_1.geometry}
                      material={materials["gelb.metal.001"]}
                    />
                  </group>
                </group>
                <group
                  name="Cube031"
                  position={[0.004, 0.178, -0.001]}
                  rotation={[-1.058, 0, 0]}
                >
                  <mesh
                    name="Cube059_1"
                    geometry={nodes.Cube059_1.geometry}
                    material={materials["gelb.metal.001"]}
                  />
                  <mesh
                    name="Cube059_2"
                    geometry={nodes.Cube059_2.geometry}
                    material={materials["Plasti.blackl"]}
                  />
                </group>
              </group>
              <group
                name="Cylinder004"
                position={[0, 0.315, 0.003]}
                rotation={[0.368, 0, 0]}
              >
                <mesh
                  name="Cylinder038"
                  geometry={nodes.Cylinder038.geometry}
                  material={materials["gelb.metal.001"]}
                />
                <mesh
                  name="Cylinder038_1"
                  geometry={nodes.Cylinder038_1.geometry}
                  material={materials["Plasti.blackl"]}
                />
              </group>
            </group>
            <mesh
              name="Cylinder019"
              geometry={nodes.Cylinder019.geometry}
              material={materials["metal-Black-grey-dird.002"]}
              position={[0, -0.004, 0.012]}
            />
          </group>
        </group>
        <group
          name="Robo_gelb003"
          position={[130.525, -0.597, -156.321]}
          rotation={[0, -1.571, 0]}
          scale={1.959}
        >
          <group name="Bone_3" position={[0.001, -0.002, -0.004]}>
            <group
              name="Bone001_3"
              position={[0, 0.038, 0]}
              rotation={[-0.368, 0, 0]}
            >
              <group
                name="Bone002_3"
                position={[0, 0.328, 0]}
                rotation={[1.426, 0, 0]}
              >
                <group
                  name="Bone003_3"
                  position={[0, 0.349, 0]}
                  rotation={[0.513, 0, 0]}
                >
                  <group
                    name="Cube041"
                    position={[-0.001, 0.013, -0.001]}
                    rotation={[-Math.PI / 2, 0, 0]}
                  >
                    <mesh
                      name="Cube060"
                      geometry={nodes.Cube060.geometry}
                      material={materials["metal-Black-grey-dird.002"]}
                    />
                    <mesh
                      name="Cube060_1"
                      geometry={nodes.Cube060_1.geometry}
                      material={materials["gelb.metal.001"]}
                    />
                  </group>
                </group>
                <group
                  name="Cube040"
                  position={[0.004, 0.178, -0.001]}
                  rotation={[-1.058, 0, 0]}
                >
                  <mesh
                    name="Cube059_1"
                    geometry={nodes.Cube059_1.geometry}
                    material={materials["gelb.metal.001"]}
                  />
                  <mesh
                    name="Cube059_2"
                    geometry={nodes.Cube059_2.geometry}
                    material={materials["Plasti.blackl"]}
                  />
                </group>
              </group>
              <group
                name="Cylinder028"
                position={[0, 0.315, 0.003]}
                rotation={[0.368, 0, 0]}
              >
                <mesh
                  name="Cylinder038"
                  geometry={nodes.Cylinder038.geometry}
                  material={materials["gelb.metal.001"]}
                />
                <mesh
                  name="Cylinder038_1"
                  geometry={nodes.Cylinder038_1.geometry}
                  material={materials["Plasti.blackl"]}
                />
              </group>
            </group>
            <mesh
              name="Cylinder030"
              geometry={nodes.Cylinder030.geometry}
              material={materials["metal-Black-grey-dird.002"]}
              position={[0, -0.004, 0.012]}
            />
          </group>
        </group>
        <mesh
          name="Cube599"
          geometry={nodes.Cube599.geometry}
          material={materials.hblaugrau}
          position={[119.528, 2.774, -162.084]}
          scale={[1.174, 0.165, 13.054]}
        />
        <mesh
          name="Kunststoff"
          geometry={nodes.Kunststoff.geometry}
          material={materials.hbl}
          position={[132.223, 2.281, -140.734]}
        />
        <mesh
          name="Logo"
          geometry={nodes.Logo.geometry}
          material={materials.NMHblau}
          position={[149.579, 2.702, -133.65]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={105.248}
        />
        <group name="fertigung" position={[127.164, 3.94, -157.91]}>
          <mesh
            name="Cube_1"
            geometry={nodes.Cube_1.geometry}
            material={materials.Glas}
          />
          <mesh
            name="Cube_2"
            geometry={nodes.Cube_2.geometry}
            material={materials.schwarz}
          />
        </group>
        <group
          name="foyer"
          position={[167.749, 2.247, -161.321]}
          scale={[2.683, 3.392, 4.261]}
        >
          <mesh
            name="Cube106"
            geometry={nodes.Cube106.geometry}
            material={materials.graublau}
          />
          <mesh
            name="Cube106_1"
            geometry={nodes.Cube106_1.geometry}
            material={materials.fenster}
          />
          <mesh
            name="Cube106_2"
            geometry={nodes.Cube106_2.geometry}
            material={materials.boden}
          />
        </group>
        <group
          name="Cube145"
          position={[112.364, 0.657, -147.344]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[0.207, 1.48, 1.605]}
        >
          <mesh
            name="Cube707"
            geometry={nodes.Cube707.geometry}
            material={materials["weiss.001"]}
          />
          <mesh
            name="Cube707_1"
            geometry={nodes.Cube707_1.geometry}
            material={materials.metall}
          />
        </group>
        <mesh
          name="Cube134"
          geometry={nodes.Cube134.geometry}
          material={materials["fenster.außen"]}
          position={[149.583, 0.913, -133.968]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[0.42, 0.996, 0.542]}
        />
        <mesh
          name="landscape"
          geometry={nodes.landscape.geometry}
          material={materials["gruen.002"]}
          position={[127.164, -5.271, -157.303]}
          scale={277.411}
        />
        <group
          name="Zug_Triebwagen"
          position={[258.182, 4.425, -40.604]}
          rotation={[0, 0.409, 0]}
          scale={1.485}
        >
          <mesh
            name="Cube014"
            geometry={nodes.Cube014.geometry}
            material={materials.rot}
          />
          <mesh
            name="Cube014_1"
            geometry={nodes.Cube014_1.geometry}
            material={materials.scheinwerfer}
          />
          <mesh
            name="Cube014_2"
            geometry={nodes.Cube014_2.geometry}
            material={materials["hgrau.001"]}
          />
        </group>
        <group
          name="LKW"
          position={[87.232, -7.52, -371.38]}
          rotation={[0, 0.276, 0]}
          scale={[1.073, 1.073, 0.952]}
        >
          <mesh
            name="Cube015"
            geometry={nodes.Cube015.geometry}
            material={materials["NMHblau.001"]}
          />
          <mesh
            name="Cube015_1"
            geometry={nodes.Cube015_1.geometry}
            material={materials["Lampe.001"]}
          />
        </group>
        <group
          name="LKW_Anhaenger"
          position={[86.762, -5.351, -372.893]}
          rotation={[0, 0.276, 0]}
          scale={40.973}
        >
          <mesh
            name="Curve001"
            geometry={nodes.Curve001.geometry}
            material={materials.rueckleuchten}
          />
          <mesh
            name="Curve001_1"
            geometry={nodes.Curve001_1.geometry}
            material={materials["dgrau.001"]}
          />
        </group>
        {/* <mesh name="sky" geometry={nodes.sky.geometry} material={materials.himmel} position={[114.145, 150.878, -262.841]} scale={[364.84, 159.203, 364.84]} /> */}
        <group
          name="Heissluftballon"
          position={[108.124, 47.186, -96.157]}
          rotation={[-Math.PI, 1.136, -Math.PI]}
          scale={169.579}
        >
          <mesh
            name="Curve002"
            geometry={nodes.Curve002.geometry}
            material={materials.Feuer}
          />
          <mesh
            name="Curve002_1"
            geometry={nodes.Curve002_1.geometry}
            material={materials.Haare}
          />
          <mesh
            name="Curve002_2"
            geometry={nodes.Curve002_2.geometry}
            material={materials.Haut}
          />
          <mesh
            name="Curve002_3"
            geometry={nodes.Curve002_3.geometry}
            material={materials.jeans}
          />
          <mesh
            name="Curve002_4"
            geometry={nodes.Curve002_4.geometry}
            material={materials.Pullover_rot}
          />
          <mesh
            name="Curve002_5"
            geometry={nodes.Curve002_5.geometry}
            material={materials["weiss.002"]}
          />
          <mesh
            name="Curve002_6"
            geometry={nodes.Curve002_6.geometry}
            material={materials["braun.002"]}
          />
          <mesh
            name="Curve002_7"
            geometry={nodes.Curve002_7.geometry}
            material={materials["schwarz.005"]}
          />
        </group>
        <group
          name="Auto"
          position={[217.928, 0.25, -49.884]}
          rotation={[0, 0.3, 0]}
          scale={[0.941, 0.81, 1.516]}
        >
          <mesh
            name="Cube184"
            geometry={nodes.Cube184.geometry}
            material={materials["graublau.002"]}
          />
          <mesh
            name="Cube184_1"
            geometry={nodes.Cube184_1.geometry}
            material={materials.Rueckleuchten}
          />
        </group>
        <group name="Fahne" position={[181.322, 1.082, -151.206]} scale={3.219}>
          <mesh
            name="Cube001"
            geometry={nodes.Cube001.geometry}
            material={materials["Fahne.001"]}
          />
          <mesh
            name="Cube001_1"
            geometry={nodes.Cube001_1.geometry}
            material={materials["hblaugrau.001"]}
          />
        </group>
        <mesh
          name="Plane005"
          geometry={nodes.Plane005.geometry}
          material={materials.gruen}
          position={[167.32, -1.058, -96.971]}
          scale={[-17.486, -12.831, -12.312]}
        />
        <mesh
          name="Zufahrtsstrasse001"
          geometry={nodes.Zufahrtsstrasse001.geometry}
          material={materials.hgrau}
          position={[100.478, -1.098, -132.798]}
          rotation={[Math.PI, -0.094, Math.PI]}
          scale={[-5.244, -0.32, -5.885]}
        />
        <mesh
          name="Gleise001"
          geometry={nodes.Gleise001.geometry}
          material={materials.hgrau}
          position={[174.288, 2.016, -294.384]}
          rotation={[0, 0.33, 0]}
          scale={[0.217, 0.263, 1.236]}
        />
        <mesh
          name="Baum1012"
          geometry={nodes.Baum1012.geometry}
          material={materials["gruen.001"]}
          position={[180.185, -0.087, -138.761]}
          rotation={[Math.PI, -0.717, Math.PI]}
          scale={[0.274, 0.843, 0.242]}
        />
        <mesh
          name="Cube003"
          geometry={nodes.Cube003.geometry}
          material={materials.brick}
          position={[167.779, 0.549, -162.166]}
        />
        <mesh
          name="Bildschirm010"
          geometry={nodes.Bildschirm010.geometry}
          material={materials["Bildschirmleuchten.005"]}
          position={[169.272, -0.025, -158.518]}
          rotation={[0, -1.233, -Math.PI / 2]}
          scale={[0.135, 0.01, 0.258]}
        />
        <group
          name="Laptop008"
          position={[168.814, 0.101, -159.371]}
          rotation={[0, 1.508, 0]}
          scale={[0.08, 0.006, 0.106]}
        >
          <mesh
            name="Cube017_1"
            geometry={nodes.Cube017_1.geometry}
            material={materials["Material.005"]}
          />
          <mesh
            name="Cube017_2"
            geometry={nodes.Cube017_2.geometry}
            material={materials["Material.006"]}
          />
        </group>
        <mesh
          name="Cube139"
          geometry={nodes.Cube139.geometry}
          material={materials["weiss.007"]}
          position={[170.065, 0.663, -152.259]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[0.226, 0.226, 0.456]}
        />
        <mesh
          name="Cube068"
          geometry={nodes.Cube068.geometry}
          material={materials.Material}
          position={[167.152, 0.379, -163.247]}
          scale={0.26}
        />
        <group
          name="Cube025"
          position={[166.688, 0.1, -159.181]}
          rotation={[0, 1.47, 0.249]}
          scale={[0.221, 0.088, 0.088]}
        >
          <mesh
            name="Cube043"
            geometry={nodes.Cube043.geometry}
            material={materials.schwarz}
          />
          <mesh
            name="Cube043_1"
            geometry={nodes.Cube043_1.geometry}
            material={materials.Glas}
          />
          <mesh
            name="Cube043_2"
            geometry={nodes.Cube043_2.geometry}
            material={materials["Bildschirmleuchten.005"]}
          />
          <mesh
            name="Cube043_3"
            geometry={nodes.Cube043_3.geometry}
            material={materials.fenster}
          />
        </group>
        <group
          name="Cube072"
          position={[166.863, 0.738, -157.871]}
          scale={[0.033, 0.148, 0.092]}
        >
          <mesh
            name="Cube044"
            geometry={nodes.Cube044.geometry}
            material={materials.NMHblau}
          />
          <mesh
            name="Cube044_1"
            geometry={nodes.Cube044_1.geometry}
            material={materials["weiss.007"]}
          />
        </group>
        <group
          name="Cube073"
          position={[165.986, 0.62, -157.871]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.033, 0.148, 0.092]}
        >
          <mesh
            name="Cube044"
            geometry={nodes.Cube044.geometry}
            material={materials.NMHblau}
          />
          <mesh
            name="Cube044_1"
            geometry={nodes.Cube044_1.geometry}
            material={materials["weiss.007"]}
          />
        </group>
        <group
          name="Cube074"
          position={[166.333, 0.716, -157.919]}
          rotation={[0, 1.47, 0.249]}
          scale={[0.221, 0.088, 0.088]}
        >
          <mesh
            name="Cube047"
            geometry={nodes.Cube047.geometry}
            material={materials.schwarz}
          />
          <mesh
            name="Cube047_1"
            geometry={nodes.Cube047_1.geometry}
            material={materials.Glas}
          />
          <mesh
            name="Cube047_2"
            geometry={nodes.Cube047_2.geometry}
            material={materials["Bildschirmleuchten.005"]}
          />
          <mesh
            name="Cube047_3"
            geometry={nodes.Cube047_3.geometry}
            material={materials.fenster}
          />
        </group>
        <group
          name="Cylinder027"
          position={[169.122, 0.299, -158.956]}
          scale={-0.036}
        >
          <mesh
            name="Cylinder"
            geometry={nodes.Cylinder.geometry}
            material={materials.drot}
          />
          <mesh
            name="Cylinder_1"
            geometry={nodes.Cylinder_1.geometry}
            material={materials.schwarz}
          />
          <mesh
            name="Cylinder_2"
            geometry={nodes.Cylinder_2.geometry}
            material={materials.metall}
          />
        </group>
        <mesh
          name="Cube030"
          geometry={nodes.Cube030.geometry}
          material={materials.Lampe}
          position={[166.168, -0.336, -159.122]}
          scale={[0.758, 0.438, 0.347]}
        />
        <group
          name="Buero_Regal3001"
          position={[168.963, -0.05, -152.364]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[0.283, 0.712, 0.686]}
        >
          <mesh
            name="Cube111"
            geometry={nodes.Cube111.geometry}
            material={materials["weiss.001"]}
          />
          <mesh
            name="Cube111_1"
            geometry={nodes.Cube111_1.geometry}
            material={materials.NMHblau}
          />
          <mesh
            name="Cube111_2"
            geometry={nodes.Cube111_2.geometry}
            material={materials["weiss.007"]}
          />
        </group>
        <group
          name="Buero_Schrank1"
          position={[166.549, 0.118, -157.752]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[0.328, 0.873, 0.368]}
        >
          <mesh
            name="Cube102"
            geometry={nodes.Cube102.geometry}
            material={materials["dgrau.001"]}
          />
          <mesh
            name="Cube102_1"
            geometry={nodes.Cube102_1.geometry}
            material={materials["braun.002"]}
          />
          <mesh
            name="Cube102_2"
            geometry={nodes.Cube102_2.geometry}
            material={materials.metall}
          />
          <mesh
            name="Cube102_3"
            geometry={nodes.Cube102_3.geometry}
            material={materials["graublau.hell"]}
          />
          <mesh
            name="Cube102_4"
            geometry={nodes.Cube102_4.geometry}
            material={materials.metall}
          />
        </group>
        <mesh
          name="Rote_Couch"
          geometry={nodes.Rote_Couch.geometry}
          material={materials.drot}
          position={[169.316, -0.688, -164.581]}
          rotation={[0, 1.505, 0]}
          scale={[0.966, 0.128, 0.966]}
        />
        <mesh
          name="Cube078"
          geometry={nodes.Cube078.geometry}
          material={materials.hblaugrau}
          position={[166.035, 0.657, -162.236]}
          scale={[1.114, 1.432, 0.092]}
        />
        <mesh
          name="Cube083"
          geometry={nodes.Cube083.geometry}
          material={materials.hblaugrau}
          position={[166.974, 0.642, -156.542]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[1.284, 1.429, 0.092]}
        />
        <group
          name="Tür001"
          position={[164.871, -0.105, -157.346]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[0.047, 0.688, 0.355]}
        >
          <mesh
            name="Cube118"
            geometry={nodes.Cube118.geometry}
            material={materials["weiss.001"]}
          />
          <mesh
            name="Cube118_1"
            geometry={nodes.Cube118_1.geometry}
            material={materials["braun.002"]}
          />
          <mesh
            name="Cube118_2"
            geometry={nodes.Cube118_2.geometry}
            material={materials.metall}
          />
        </group>
        <mesh
          name="Tisch"
          geometry={nodes.Tisch.geometry}
          material={materials["beige.001"]}
          position={[166.415, -0.1, -168.959]}
          scale={[0.538, 0.023, 0.916]}
        />
        <mesh
          name="Bildschirm"
          geometry={nodes.Bildschirm.geometry}
          material={materials["Bildschirmleuchten.002"]}
          position={[166.423, 0.191, -170.658]}
          rotation={[Math.PI / 2, -Math.PI / 2, 0]}
          scale={[0.412, 0.019, 0.745]}
        />
        <mesh
          name="Cube595"
          geometry={nodes.Cube595.geometry}
          material={materials["graublau.003"]}
          position={[165.344, 2.095, -161.756]}
          scale={[1, 0.057, 1]}
        />
        <mesh
          name="Bildschirm002"
          geometry={nodes.Bildschirm002.geometry}
          material={materials.Bildschirmleuchten}
          position={[164.236, 0.191, -154.43]}
          rotation={[-Math.PI, 0, Math.PI / 2]}
          scale={[0.412, 0.019, 0.745]}
        />
        <mesh
          name="Buero_Schrank1001"
          geometry={nodes.Buero_Schrank1001.geometry}
          material={materials["graublau.hell"]}
          position={[155.458, -0.167, -159.142]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[0.263, 0.698, 0.498]}
        />
        <mesh
          name="Cube"
          geometry={nodes.Cube.geometry}
          material={materials["orange.002"]}
          position={[143.869, 0.295, -168.423]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[0.097, 1.257, 0.097]}
        />
        <mesh
          name="Cube059"
          geometry={nodes.Cube059.geometry}
          material={materials["Bildschirmleuchten.003"]}
          position={[129.109, 0.379, -168.256]}
          scale={[0.034, 0.025, 0.025]}
        />
        <group
          name="Cube066"
          position={[123.945, 2.202, -160.172]}
          scale={[2.997, 2.957, 3.013]}
        >
          <mesh
            name="Cube179"
            geometry={nodes.Cube179.geometry}
            material={materials["hblaugrau.Fertigung.001"]}
          />
          <mesh
            name="Cube179_1"
            geometry={nodes.Cube179_1.geometry}
            material={materials["hblaugrau.boden"]}
          />
        </group>
        <mesh
          name="Cube097"
          geometry={nodes.Cube097.geometry}
          material={materials.Ausbildung_Boden}
          position={[125.152, -0.716, -167.136]}
          scale={[3.163, 0.037, 1]}
        />
        <group
          name="Montageplatz1004"
          position={[122.348, -0.624, -169.5]}
          rotation={[0, 0.001, 0]}
          scale={[0.354, 0.015, 0.602]}
        >
          <mesh
            name="Cube082"
            geometry={nodes.Cube082.geometry}
            material={materials["dgrau.003"]}
          />
          <mesh
            name="Cube082_1"
            geometry={nodes.Cube082_1.geometry}
            material={materials["dblau.003"]}
          />
        </group>
        <mesh
          name="Cube660"
          geometry={nodes.Cube660.geometry}
          material={materials.hblaugrau}
          position={[132.218, 8.513, -160.202]}
          scale={[24.158, 3.294, 6.742]}
        />
        <mesh
          name="Cube665"
          geometry={nodes.Cube665.geometry}
          material={materials.hblaugrau}
          position={[129.913, 5.556, -161.821]}
          scale={[2.93, 3.227, 3.412]}
        />
        <group
          name="Schwerlastregal_voll"
          position={[140.499, 0.678, -163.549]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[0.098, 0.094, 0.179]}
        >
          <mesh
            name="Cube027"
            geometry={nodes.Cube027.geometry}
            material={materials.gelb}
          />
          <mesh
            name="Cube027_1"
            geometry={nodes.Cube027_1.geometry}
            material={materials["Deep.Black"]}
          />
        </group>
        <mesh
          name="Cube092"
          geometry={nodes.Cube092.geometry}
          material={materials.teppichboden}
          position={[151.109, 0.261, -166.735]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[3.991, 1, 0.092]}
        />
        <mesh
          name="Bildschirm004"
          geometry={nodes.Bildschirm004.geometry}
          material={materials["weiß-metall"]}
          position={[153.779, 0.11, -168.882]}
          rotation={[Math.PI / 2, -Math.PI / 2, 0]}
          scale={[0.163, 0.01, 0.287]}
        />
        <mesh
          name="M_3D"
          geometry={nodes.M_3D.geometry}
          material={materials["gruen_leuchten.001"]}
          position={[136.229, -0.354, -163.184]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[0.542, 0.542, 0.864]}
        />
        <mesh
          name="M_6F"
          geometry={nodes.M_6F.geometry}
          material={materials["metall-weiß"]}
          position={[127.778, 0.152, -156.842]}
          rotation={[0, -1.571, 0]}
          scale={[0.881, 1.008, 0.881]}
        />
        <mesh
          name="Cube013"
          geometry={nodes.Cube013.geometry}
          material={materials["dblau.metal"]}
          position={[124.964, 0.268, -148.713]}
          scale={[0.674, 1, 0.863]}
        />
        <mesh
          name="Fließband"
          geometry={nodes.Fließband.geometry}
          material={materials["metal-grey-dird.001"]}
          position={[134.115, 0.161, -151.832]}
          rotation={[-Math.PI, 0, 0]}
          scale={[3.894, 0.011, 0.034]}
        />
        <mesh
          name="Cube010"
          geometry={nodes.Cube010.geometry}
          material={materials["Plasti.blackl"]}
          position={[133.575, -0.589, -150.491]}
          scale={[0.826, 0.489, 0.826]}
        />
        <mesh
          name="Cube021"
          geometry={nodes.Cube021.geometry}
          material={materials["Gitter-blau"]}
          position={[134.176, -0.038, -150.187]}
          rotation={[-Math.PI, 0, 0]}
          scale={[-5.61, -0.695, -2.543]}
        />
        <mesh
          name="Tisch002"
          geometry={nodes.Tisch002.geometry}
          material={materials["Weiss_acrül.001"]}
          position={[137.063, -0.559, -156.967]}
          rotation={[0, -1.571, 0]}
          scale={1.959}
        />
        <mesh
          name="Cube168"
          geometry={nodes.Cube168.geometry}
          material={materials.Bildschirmleuchten}
          position={[152.307, 1.643, -158.522]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[-0.306, -0.073, -0.205]}
        />
        <mesh
          name="Cube063"
          geometry={nodes.Cube063.geometry}
          material={materials["metall-grau"]}
          position={[138.693, -0.812, -165.2]}
          rotation={[0, 0, -0.201]}
          scale={[0.144, 0.02, 0.586]}
        />
        <mesh
          name="Cube116"
          geometry={nodes.Cube116.geometry}
          material={materials["metall-weiß.002"]}
          position={[121.731, 1.56, -137.026]}
          scale={[1.204, 0.075, 2.829]}
        />
        <mesh
          name="M_1K"
          geometry={nodes.M_1K.geometry}
          material={materials["Material.007"]}
          position={[144.993, -0.016, -144.048]}
          scale={[0.432, 0.473, 0.707]}
        />
        <mesh
          name="M_1K003"
          geometry={nodes.M_1K003.geometry}
          material={materials["Maschine innen"]}
          position={[143.259, -0.016, -143.98]}
          scale={[0.432, 0.473, 0.707]}
        />
        <mesh
          name="wand001"
          geometry={nodes.wand001.geometry}
          material={nodes.wand001.material}
          position={[136.476, 0.221, -175.097]}
          scale={[1.284, 1, 0.092]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/NVM.glb");
